### PR TITLE
Travis: added PHP 7.4

### PR DESCRIPTION
**Pull request by k00ni**

### CODE REVIEW

**Comment by k00ni** [comment]
@pietercolpaert any idea why this fails in PHP 7.4?

**Comment by pietercolpaert** [comment]
No idea in fact: it’s been a while since I’ve touched PHP7.4. I’ll add the help needed label to this one.

**Comment by k00ni** [comment]
I've found the problem of the failing test. In the `writeLine` closure (https://github.com/pietercolpaert/hardf/pull/28/files#diff-9c92b3d694a210ad957dbb820aa88a98L78-R82) the following line breaks in PHP 7.4:

> $this->graph = $graph[0] !== '[' ? $graph : ']';

because `$graph` can be `null`. In the code is no check if `$graph` is an array or not. I found it after I enabled exceptions to get passed to caller, if arise. Before that, all exceptions were swallowed, including the PHP error complaining about null.

**Comment by k00ni** [comment]
Outdated, because #29 also included these changes.

**Pull request closed without merging**
