### PR TITLE
Rework code (less JS, more PHP like), added tooling for development (PHPStan, PHP-CS-Fixer)

### PR DESCRIPTION
**Pull request by k00ni**
I wanted to see if I can fix failing tests in PHP 7.4 (#28), ended up reworked many parts to get cleaner code and a better view on what is happening.

**tl;dr:** hardf code is way to much JS-like and not using proper PHP-concepts. For instance, hot swapping closures during parsing. That may feel handy, but it makes error-tracing so much harder (also static analysis). Further tooling added to make development more smooth.

@pietercolpaert: its a total overhaul of your code, hope its not too much at once.

**Problems / issues**
* TriGWriterTest uses `shouldNotSerialize`, which is called with parameters (even though this method hasn't any) and has no implementation (ref: https://github.com/pietercolpaert/hardf/blob/master/test/TriGWriterTest.php#L552).
* TriGWriter
  * calls `write` with 2 parameters, but this method only has 1 (`$done` parameter not used in function) -- **Therefore** `$done` can be removed as parameter and all callers have to be adapted to not use $done anymore.
  * its `end` function has no parameters, but is used in tests with 1 parameter (e.g. `TriGWriterTest::shouldSerialize`).
  * Closures for `writeTriple` and `writeTripleLine` calling `$done` parameter (callable or null), if set. If not set, all raised exceptions get swallowed up. As far as I can tell, all tests around `shouldSerialize` and `shouldNoSerialize` in `TriGWriter` are not trustworthy, because errors are not passed from source to test. **tl;dr**: Thrown exceptions need to reach the caller, so it can be handled properly. But that is not the case.
  * because of swallowed error messages, I couldn't find any sign why tests fail in PHP 7.4 (#28) at the beginning
* reduced the amount of closures; instead use "real" functions with types in parameter list and return type.
* removed a lot of commented code in the tests (mostly not ported JS code)
* In `N3Lexer` there is a function call like `callback(null, ['line' => $this->line, 'type' => 'comment', 'value' => $comment[1], 'prefix' => '']);`. If I see that right, `callback` is from PHPUnit and not available without it. Reference: https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Assert/Functions.php#L2045 - @pietercolpaert can you approve that?

**Further changes:**
* [x] set minimum PHP version in `composer.json` to 7.1 (all version below 7.2 are not maintained anymore, but 7.1 may be used still, so i leave it for now)
* [x] added a few tools, which help us in the long run by making development easier (e.g. find dead code, keep coding styles):
  * [x] PHPStan for static code analysis (helps finding dead code, wrong type usage on variables etc.)
  * [x] PHP-CS-Fixer to maintain more readable code
* [x] made code more PHP-like (e.g. reduced amount of closures, removed JS-styled test calls like `//it('does not work with null', function () {//TODO: Util::getLiteralType.bind(null, null).should.throw('null is not a literal');`
* [x] added `.editorconfig` file to further help with keep our coding standards (if editor supports it)

What do you think?

### CODE REVIEW

**Review by pietercolpaert — APPROVED** [review]
Looks good @k00ni! I haven’t written PHP since this repo and I don’t know what lives in the PHP community nowadays. I trust you that these changes will make sure the code is of a higher quality!

**Comment by k00ni** [comment]
Thank you for your trust. First I was hesitant because changed a lot of your initial code, but thinking about the long run changed my mind. My approach was to keep your concepts and style if possible, but implement it using more-or-less state of the art PHP. The whole PHP ecosystem changes towards more type-oriented programming, for instance. Also having a known coding style, like PSR-2, helps foreign developers to understand your code.

**Comment by k00ni** [comment]
We can leave this PR open, in case you wanna make additional performance checks for instance.

**Comment by pietercolpaert** [comment]
I think it’s better to move faster and release the higher quality PHP code, so that future pull requests can be based on that. What do you think?

**Pull request merged**
